# Generated by Django 3.1.1 on 2022-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20220215_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='account_profile',
            name='mobile',
            field=models.CharField(default='', max_length=25),
        ),
    ]
