# Generated by Django 3.1.1 on 2022-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_account_profile_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='verified',
            field=models.CharField(default='not verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='account_profile',
            name='verification',
            field=models.CharField(default='', max_length=20),
        ),
    ]
