# Generated by Django 3.1.1 on 2022-03-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_accnt_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accnt_profile',
        ),
        migrations.RemoveField(
            model_name='account_profile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='account_profile',
            name='verified',
        ),
    ]
