# Generated by Django 3.1.1 on 2022-03-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_auto_20220315_1803'),
        ('lib', '0007_auto_20220315_2031'),
    ]

    operations = [
    ]
