# Generated by Django 3.1.1 on 2022-03-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_merge_20220315_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_profile',
            name='verification',
        ),
    ]
