# Generated by Django 3.1.1 on 2022-03-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_remove_account_profile_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='verify',
            field=models.CharField(default='', max_length=10),
        ),
    ]
