# Generated by Django 3.1.1 on 2022-03-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_account_profile_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_profile',
            name='verify',
            field=models.CharField(default='', max_length=20),
        ),
    ]
