# Generated by Django 3.1.1 on 2022-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0013_auto_20220321_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_business_info',
            name='rootid',
            field=models.CharField(default='', max_length=80),
        ),
    ]
