# Generated by Django 3.1.1 on 2022-03-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0016_auto_20220324_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_business_info',
            name='regCertificate',
        ),
        migrations.RemoveField(
            model_name='t_business_info',
            name='registrationNumber',
        ),
    ]
