# Generated by Django 3.1.1 on 2022-04-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0017_auto_20220324_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_business_info',
            name='idCard',
        ),
        migrations.RemoveField(
            model_name='t_business_info',
            name='idType',
        ),
    ]
