# Generated by Django 3.1.1 on 2022-04-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0018_auto_20220403_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_business_info',
            name='dob',
        ),
    ]
