# Generated by Django 3.1.1 on 2022-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0020_auto_20220412_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_business_info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='t_business_info',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='t_business_info',
            name='rootid',
            field=models.CharField(default='', max_length=80),
        ),
    ]
