# Generated by Django 3.1.1 on 2022-04-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0022_auto_20220412_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_business_info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='t_business_info',
            name='mobile',
        ),
    ]
