# Generated by Django 3.1.1 on 2022-04-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0023_auto_20220412_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_business_info',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='t_business_info',
            name='owner',
            field=models.CharField(default='', max_length=80),
        ),
    ]
