# Generated by Django 3.1.1 on 2022-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0024_auto_20220412_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_business_info',
            name='owner',
        ),
        migrations.AddField(
            model_name='t_business_info',
            name='mobile',
            field=models.CharField(default='', max_length=25),
        ),
    ]
