# Generated by Django 3.1.1 on 2022-04-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0025_auto_20220412_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_business_info',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='t_business_info',
            name='postalCode',
        ),
    ]
