# Generated by Django 3.2.5 on 2021-08-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0003_auto_20210804_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcctAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(default='active', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
