# Generated by Django 3.2.5 on 2021-08-19 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0004_acctattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='acctattributes',
            name='sponser',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
