# Generated by Django 3.2.5 on 2021-08-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0005_acctattributes_sponser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acctattributes',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='acctattributes',
            name='sponser',
            field=models.CharField(max_length=50),
        ),
    ]
