# Generated by Django 3.2.5 on 2021-09-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0006_auto_20210819_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
