# Generated by Django 3.2.5 on 2021-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0007_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
