# Generated by Django 3.1.1 on 2022-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0010_auto_20220118_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
    ]
