# Generated by Django 3.1.1 on 2022-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0012_products_moq'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='measurementType',
            field=models.CharField(default='Kilograms', max_length=20),
        ),
    ]
