# Generated by Django 3.1.1 on 2022-01-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0014_t_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=500)),
                ('status', models.CharField(default='active', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rootid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='libs.products')),
            ],
        ),
    ]
