# Generated by Django 3.1.1 on 2022-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0016_auto_20220124_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
