# Generated by Django 3.1.1 on 2022-01-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0017_auto_20220125_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
