# Generated by Django 3.1.1 on 2022-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0019_auto_20220125_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.CharField(default='Ready to ship', max_length=20),
        ),
    ]
