# Generated by Django 3.1.1 on 2022-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0021_contact_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
