# Generated by Django 3.1.1 on 2022-02-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0024_secondsubcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcctAttributes',
        ),
        migrations.DeleteModel(
            name='DeployedTickets',
        ),
    ]
