# Generated by Django 3.2.5 on 2022-02-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0027_auto_20220215_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_supplier',
            name='enquirer',
        ),
    ]
